#!/usr/bin/env bash
# Generate strong secrets for FBM channel + write to .env.fbm (chmod 600).
# Idempotent: if .env.fbm already exists with all required keys, exits 0 without changes.
#
# Usage: ./setup-secrets.sh /opt/goclaw [--force]

set -euo pipefail
umask 0077

GOCLAW_DIR="${1:?GoClaw dir required as first arg}"
FORCE="${2:-}"

ENV_FILE="$GOCLAW_DIR/.env.fbm"

REQUIRED_KEYS=(FBM_AUTH_TOKEN FBM_HMAC_SECRET SYNAPSE_ADMIN_TOKEN FBM_PORT)

has_all_keys() {
  [[ -f "$1" ]] || return 1
  for k in "${REQUIRED_KEYS[@]}"; do
    grep -q "^${k}=" "$1" || return 1
  done
  return 0
}

if has_all_keys "$ENV_FILE" && [[ "$FORCE" != "--force" ]]; then
  echo "  ✓ $ENV_FILE already complete (use --force to regenerate)"
  exit 0
fi

# Back up existing file if present
if [[ -f "$ENV_FILE" ]]; then
  cp -a "$ENV_FILE" "$ENV_FILE.bak-$(date +%Y%m%d%H%M%S)"
fi

FBM_AUTH_TOKEN=$(openssl rand -hex 32)
FBM_HMAC_SECRET=$(openssl rand -hex 32)
SYNAPSE_ADMIN_TOKEN=$(openssl rand -hex 32)

cat > "$ENV_FILE" <<EOF
# Generated by install-fbm-bundle.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit to git. File mode must be 600.
FBM_AUTH_TOKEN=$FBM_AUTH_TOKEN
FBM_HMAC_SECRET=$FBM_HMAC_SECRET
SYNAPSE_ADMIN_TOKEN=$SYNAPSE_ADMIN_TOKEN
FBM_PORT=29320
FBM_INSTANCE_NAME=default
EOF
chmod 600 "$ENV_FILE"
echo "  ✓ Secrets written to $ENV_FILE (chmod 600)"
